"""Utility package for research summarization and orchestration tools."""

from .meta_orchestration import (
    AuditEntry,
    AuditLog,
    BrowserOrchestrationProtocol,
    BrowserTabState,
    BrowserTransition,
    EmergentTacticDetector,
    MetaOrchestrationFramework,
    MetaPromptTracker,
    MetaPromptVersion,
    ParadoxCatalog,
    ParadoxEntry,
    PlanOfWorkEntry,
    PlanOfWorkMatrix,
    PhaseRecord,
    ResearchAgent,
    RoleDefinition,
    RoleOverlap,
    RoleResponsibilityLedger,
    StrategicArchitecture,
    StrategicComponent,
    TestScenario,
    TestingStrategy,
)
from .summarizer import ResearchSummaryGenerator, SummaryResult

__all__ = [
    "AuditEntry",
    "AuditLog",
    "BrowserOrchestrationProtocol",
    "BrowserTabState",
    "BrowserTransition",
    "EmergentTacticDetector",
    "MetaOrchestrationFramework",
    "MetaPromptTracker",
    "MetaPromptVersion",
    "ParadoxCatalog",
    "ParadoxEntry",
    "PlanOfWorkEntry",
    "PlanOfWorkMatrix",
    "PhaseRecord",
    "ResearchAgent",
    "ResearchSummaryGenerator",
    "RoleDefinition",
    "RoleOverlap",
    "RoleResponsibilityLedger",
    "StrategicArchitecture",
    "StrategicComponent",
    "SummaryResult",
    "TestScenario",
    "TestingStrategy",
]
